kind: pipeline
name: default

platform:
  os: linux
  arch: arm64
  
workspace:
  base: /go
  path: src/github.com/go-park-mail-ru/2019_1_qwerty

steps:
- name: build_main
  image: golang:1.12-alpine
  commands:
  - cd main/
  - export GO111MODULE=on
  - export PATH=$PATH:/go
  - apk add git build-base
  - go build
#   - go test ./...
  
- name: build_auth
  image: golang:1.12-alpine
  commands:
  - cd auth/
  - export GO111MODULE=on
  - export PATH=$PATH:/go
  - apk add git build-base
  - go build
#   - go test ./...

- name: build_auth2
  image: golang:1.12-alpine
  commands:
  - cd auth2/
  - export GO111MODULE=on
  - export PATH=$PATH:/go
  - apk add git build-base
  - go build
#   - ls -la
  

# - name: notify
#   image: appleboy/drone-telegram
#   settings:
#     token: 
#       from_secret: tg_tocken
#     to:
#       from_secret: tg_user
#     message: >
#       {{#success build.status}}
#         build {{build.number}} succeeded. Good job.
#       {{else}}
#         build {{build.number}} failed. Fix me please.
#       {{/success}}
#   when:
#     status: success

- name: deploy
  image: appleboy/drone-scp
  settings:
    key:
      from_secret: ssh_key
    host: 
      from_secret: host
    username:
      from_secret: username
    port: 
      from_secret: port
    command_timeout: 3m
    target: ~/deploy
    source:
    - main/2019_1_qwerty
    - main/sql/*.sql
    - auth/auth
    - auth2/auth2
    - nginx/*
    
# - name: deploy
#   image: appleboy/drone-ssh
#   settings:
#     key:
#       from_secret: ssh_key
#     host: 
#       from_secret: host
#     username:
#       from_secret: username
#     port: 
#       from_secret: port
#     command_timeout: 3m
#     script:
#       - cd deploy
#       - rm -rf backend
#       - git clone https://github.com/go-park-mail-ru/2019_1_qwerty.git backend
#       - docker-compose up -d --no-deps --build
#   when:
#     branch:
#     - master
