version: '3.5'

services:
  proxy:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/public:/frontend/public:ro
      #- ./etc/nginx/conf.d/git-http.conf:/etc/nginx/conf.d/git-http.conf:ro"
      - ./log/nginx:/var/log/nginx
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ../certs:/etc/letsencrypt/live/site:ro
    environment:
      - NGINX_SERVERNAME="brbrroman.ru"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - backend_s3
    restart: on-failure

  backend:
    build: main/.
    container_name: backend_main
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - backend_postgres
      - backend_s3
      - backend_auth
    restart: on-failure

  backend_auth:
    build: auth/.
    container_name: backend_auth
    env_file:
      - .env
    depends_on:
      - backend_redis
    restart: on-failure

  backend_auth2:
    build: auth2/.
    container_name: backend_auth2
    env_file:
      - .env
    depends_on:
      - backend_postgres
    restart: on-failure

  backend_postgres:
    image: postgres:11-alpine
    container_name: backend_postgres
    restart: on-failure

  backend_redis:
    image: redis:5-alpine
    container_name: backend_redis
    restart: on-failure

  backend_s3:
    image: minio/minio
    container_name: backend_s3
    env_file:
      - .env
    command: server /data
    restart: on-failure
