// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson176fe525Decode20191QwertyMainModels(in *jlexer.Lexer, out *Logs) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "action":
			out.Head = string(in.String())
		case "content":
			if m, ok := out.Content.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Content.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Content = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson176fe525Encode20191QwertyMainModels(out *jwriter.Writer, in Logs) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"action\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Head))
	}
	if in.Content != nil {
		const prefix string = ",\"content\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if m, ok := in.Content.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Content.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Content))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Logs) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson176fe525Encode20191QwertyMainModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Logs) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson176fe525Encode20191QwertyMainModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Logs) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson176fe525Decode20191QwertyMainModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Logs) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson176fe525Decode20191QwertyMainModels(l, v)
}
func easyjson176fe525Decode20191QwertyMainModels1(in *jlexer.Lexer, out *IncomeLogs) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "action":
			out.Head = string(in.String())
		case "content":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Content).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson176fe525Encode20191QwertyMainModels1(out *jwriter.Writer, in IncomeLogs) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"action\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Head))
	}
	if len(in.Content) != 0 {
		const prefix string = ",\"content\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Content).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v IncomeLogs) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson176fe525Encode20191QwertyMainModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v IncomeLogs) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson176fe525Encode20191QwertyMainModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *IncomeLogs) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson176fe525Decode20191QwertyMainModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *IncomeLogs) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson176fe525Decode20191QwertyMainModels1(l, v)
}
